version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:5000"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 screener_app:app --timeout 5400
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
